version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:current
    working_directory: ~/project
jobs:
  deploy_localhost:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Serve HTML on localhost
          command: |
            python3 -m http.server 8000
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_localhost